var searchData=
[
  ['salmon',['Salmon',['../classTestSushi_1_1src_1_1Suchi_1_1Salmon.html',1,'TestSushi::src::Suchi']]],
  ['salmon',['Salmon',['../classSuchi_1_1Salmon.html',1,'Suchi']]],
  ['screen',['Screen',['../classTestSushi_1_1src_1_1Suchi_1_1Screen.html',1,'TestSushi::src::Suchi']]],
  ['screen',['Screen',['../classSushis_1_1src_1_1Screen.html',1,'Sushis::src']]],
  ['screen',['Screen',['../classmain_1_1Screen.html',1,'main']]],
  ['screen',['Screen',['../classSuchi_1_1Screen.html',1,'Suchi']]],
  ['screen',['Screen',['../classScreen.html',1,'']]],
  ['screencapturerectangle',['ScreenCaptureRectangle',['../classScreenCaptureRectangle.html',1,'']]],
  ['screencapturerectangle',['ScreenCaptureRectangle',['../classTestSushi_1_1src_1_1Suchi_1_1ScreenCaptureRectangle.html',1,'TestSushi::src::Suchi']]],
  ['screencapturerectangle',['ScreenCaptureRectangle',['../classSuchi_1_1ScreenCaptureRectangle.html',1,'Suchi']]],
  ['screenmouse',['ScreenMouse',['../classSuchi_1_1ScreenMouse.html',1,'Suchi']]],
  ['screenmouse',['ScreenMouse',['../classTestSushi_1_1src_1_1Suchi_1_1ScreenMouse.html',1,'TestSushi::src::Suchi']]],
  ['searchratio',['SearchRatio',['../classSearchRatio.html',1,'']]],
  ['service',['Service',['../classService.html',1,'']]],
  ['service',['Service',['../classmain_1_1Service.html',1,'main']]],
  ['shrimpsh',['ShrimpSh',['../classSuchi_1_1ShrimpSh.html',1,'Suchi']]],
  ['shrimpsh',['ShrimpSh',['../classTestSushi_1_1src_1_1Suchi_1_1ShrimpSh.html',1,'TestSushi::src::Suchi']]],
  ['stop',['Stop',['../classStop.html',1,'']]],
  ['sushis',['Sushis',['../enumTestSushi_1_1src_1_1Suchi_1_1Client_1_1Sushis.html',1,'TestSushi::src::Suchi::Client']]],
  ['sushis',['Sushis',['../enumSuchi_1_1Client_1_1Sushis.html',1,'Suchi::Client']]]
];
